---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  name: ${cluster_name}-${controlplane_nodes[0]}
spec:
  clusterConfiguration:
    apiServer:
      extraArgs:
        enable-admission-plugins: ${options.admission_controllers}