%{ for controlplane_node in controlplane_nodes ~}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AWSMachine
metadata:
  name: ${cluster_name}-${controlplane_node}
spec:
  ami:
    id: ${ami_id}
%{ endfor ~}
%{ for worker_node, replicas in worker_nodes ~}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AWSMachineTemplate
metadata:
  name: ${cluster_name}-${worker_node}
spec:
  template:
    spec:
      ami:
        id: ${ami_id}
%{ endfor ~}