apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: ${cluster_name}
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: AWSCluster
    name: ${cluster_name}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AWSCluster
metadata:
  name: ${cluster_name}
spec:
  region: ${aws_region}
  sshKeyName: ${ec2_key_pair}