apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ./manifests

patchesStrategicMerge:
%{ for strategic_merge_patch_file in strategic_merge_patch_files ~}
- ./patches-strategic-merge/${strategic_merge_patch_file}
%{ endfor ~}
%{ if cni == "amazon-vpc" ~}
- ./patches-strategic-merge/kubelet-node-ip-patch.yaml
%{ endif ~}


# For future use
# patchesJson6902: