apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ./manifests

patchesStrategicMerge:
%{ if vpc_id != "" ~}
- ./patches-strategic-merge/networkspec-patch.yaml
%{ endif ~}
%{ if security_group_ids != [] ~}
- ./patches-strategic-merge/additional-security-groups-patch.yaml
%{ endif ~}
%{ if ami_id != "" ~}
- ./patches-strategic-merge/ami-patch.yaml
%{ endif ~}
%{ if cni == "amazon-vpc" ~}
- ./patches-strategic-merge/kubelet-node-ip-patch.yaml
%{ endif ~}
%{ if options.admission_controllers != "" ~}
- ./patches-strategic-merge/admission-controllers-patch.yaml
%{ endif ~}
%{ if options.sa_token_volume_projection != "disabled" ~}
- ./patches-strategic-merge/sa-token-vol-proj-patch.yaml
%{ endif ~}

# For future use
# patchesJson6902: